### PR TITLE
Remove unsupported params from Species.name_usage

### LINKED ISSUE #73: Species `name_usage` params include unsupported parameters
The following params on the Species `name_usage` method are not supported and do not work:

- key
- data
- uuid
- rank
- shortname

These parameters are not listed for this search method on https://www.gbif.org/developer/species

Details on each below, and a PR forthcoming.

**key**

I cannot seem to find any key that has any effect when passed in here. The result set always begins with taxonID=>gbif:0 and seems to include everything.

**data**
I saved the results for:

https://api.gbif.org/v1/species?name=Puma%20concolor

and

https://api.gbif.org/v1/species?name=Puma%20concolor&data=all

The files were identical when diffed.

**uuid**

The comments in the code say this should work the same as datasetKey

```ruby
test = species.name_usage(name: 'Andropogon', datasetKey: '3f8a1297-3259-4700-91fc-acc4170b27ce')
test['results'].length
=> 2
test['results'].each{ |r| puts r['key'] }
100015804
100015805
```

But it does not:

```ruby
test = species.name_usage(name: 'Andropogon', uuid: '3f8a1297-3259-4700-91fc-acc4170b27ce')
test['results'].length
=> 89
test['results'].first['key']
=> 2706077
test['results'].last['key']
=> 181589405
```

It has no effect, and produces the same results as passing only the `name` parameter:

```ruby
test = species.name_usage(name: 'Andropogon')
test['results'].length
=> 89
test['results'].first['key']
=> 2706077
test['results'].last['key']
=> 181589405
```

**rank**

Does not seem to have any effect:

```ruby
test = species.name_usage(name: 'Helianthus', rank: 'SPECIES')
test['results'].map{ |t| t['rank'] }.tally
=> {"GENUS"=>64, nil=>2, "SPECIES"=>2}

test = species.name_usage(name: 'Helianthus')
test['results'].length
=> 68
```

**shortname**

The comments in the code say: A short name..need more info on this?

I'm not seeing it documented in the Species API at all. It's referenced in terms of the `/species/root/{uuid|shortname}` route, but that is not the root being used by this `name_usage` method.

### PR DESCRIPTION
**Pull request by kspurgin**
Resolves #73 
- remove unsupported params from `Species.name_usage`
- add test coverage for `Species.name_usage`

### CODE REVIEW

**Comment by kspurgin** [comment]
Hmm, tests were passing for me when I put this in and ran them on my machine. I can poke at them after work if it's an in-the-code thing and not more a CI environment thing.

**Comment by sckott** [comment]
I just approved CI running here - looks like [vcr cassettes need to be re-created](https://github.com/sckott/gbifrb/pull/74/checks?check_run_id=2494760466#step:5:28). I can do that after merging, or you can update them if you like

**Comment by kspurgin** [comment]
Either way is fine with me. Whatever's easiest for you at this point. Thanks!

**Comment by sckott** [comment]
Sorry for the very long delay!

**Comment by kspurgin** [comment]
Zero worries! I haven't really gotten back to the "weekend project" I was doing when I ran into this. I appreciate your work!

**Comment by sckott** [comment]
okay, well fwiw i'll try to push [v0.2](https://github.com/sckott/gbifrb/milestone/1) to rubygems this week

**Pull request merged**
